// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUlU3rN5brM99wd2fcZk9EJcTVmXIuDKw',
    appId: '1:317410504535:web:2b221ca4758545d5d35812',
    messagingSenderId: '317410504535',
    projectId: 'tennischamppose',
    authDomain: 'tennischamppose.firebaseapp.com',
    storageBucket: 'tennischamppose.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkXwFf_skIwDEujoH2SEZMgQtlEAsq0xw',
    appId: '1:317410504535:android:4523b2bbf7259537d35812',
    messagingSenderId: '317410504535',
    projectId: 'tennischamppose',
    storageBucket: 'tennischamppose.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3VMotB9PIC6BZURjjltn1rBg-IO8CuXs',
    appId: '1:317410504535:ios:b59d1d01f9acd900d35812',
    messagingSenderId: '317410504535',
    projectId: 'tennischamppose',
    storageBucket: 'tennischamppose.appspot.com',
    iosClientId: '317410504535-sq5qsh035qvgb1ji6pfhak80um5vhlbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennischamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3VMotB9PIC6BZURjjltn1rBg-IO8CuXs',
    appId: '1:317410504535:ios:b59d1d01f9acd900d35812',
    messagingSenderId: '317410504535',
    projectId: 'tennischamppose',
    storageBucket: 'tennischamppose.appspot.com',
    iosClientId: '317410504535-sq5qsh035qvgb1ji6pfhak80um5vhlbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennischamp',
  );
}
